language: python
cache:
  - apt
  - pip
python:
  - "3.6"
  - "3.7"
  - "3.8"
before_install:
  - pip install pipenv --upgrade
script:
  - pipenv install --dev
  - pytest
sudo: false
notifications:
  slack: watchcloud:rNoT5kJJakPqwLSKuev6oa4C
